---
name: admin_dashboard
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fluro: ^2.0.3
  google_fonts: ^3.0.1
  provider: ^6.0.3
  email_validator: ^2.1.17
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  file_picker: ^5.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/
